name: Daily Pipeline

on:
  schedule:
    - cron: '0 12 * * *'  # Executa todos os dias ao meio-dia UTC
  workflow_dispatch:       # Permite rodar manualmente

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar Script de Pipeline
        run: python3 main.py
